name: Ubuntu

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build gcc-multilib g++-multilib libunwind-dev
        sudo apt-get install libefl-all-dev
        sudo apt-get install python3-pip
        sudo apt-get install libturbojpeg0-dev libpng-dev libwebp-dev
        sudo apt-get install libglew-dev libglfw3-dev
        sudo pip3 install meson

    - name: Build
      run: |
        meson setup build -Dlog=true -Dexamples=true -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtools="all" -Dwindows=true
        sudo ninja -C build install

  static_loaders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build gcc-multilib g++-multilib
        sudo apt-get install libglew-dev libglfw3-dev
        sudo apt-get install python3-pip
        sudo pip3 install meson

    - name: Build
      run: |
        meson setup --prefix=`pwd`/static --default-library static -Dlog=true -Dbuildtype=debug -Dstrip=false -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtools="all" -Dstatic=true -Dwindows=true build .
        sudo ninja -C build install

    - name: Tar_files
      run: |
        mkdir ${{github.workspace}}/tar
        ls -all
        cd ${{github.workspace}}/static/ && tar -czvf ${{github.workspace}}/tar/thorvg_linux64_static.tgz *

    - uses: actions/upload-artifact@v4
      with:
        name: horvg_linux64_static
        path: ${{github.workspace}}/tar

  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build gcc-multilib g++-multilib libgtest-dev cmake cmake-data libasan5 valgrind
        sudo apt-get install curl jq
        sudo apt-get install software-properties-common
        sudo apt-get install python3-pip
        sudo apt-get install libturbojpeg0-dev libpng-dev libwebp-dev
        sudo apt-get install libglew-dev libglfw3-dev
        sudo pip3 install meson

    - name: Build
      run: |
        meson setup build -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtests=true --errorlogs
        sudo ninja -C build install test

    - uses: actions/upload-artifact@v4
      with:
        name: UnitTestReport
        path: build/meson-logs/testlog.txt

    - name: Run memcheck Script(valgrind)
      run: |
        export PATH=$PATH:~/.local/bin/
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/memcheck_valgrind.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/memcheck_valgrind.sh"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Run memcheck Script(ASAN)
      run: |
        sudo rm -rf ./build
        meson setup build -Db_sanitize="address,undefined" -Dloaders="all, webp_beta" -Dsavers="all" -Dtests="true" -Dbindings="capi"
        sudo ninja -C build install
        export PATH=$PATH:~/.local/bin/
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/memcheck_asan.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/memcheck_asan.sh"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
