name: Mac_bin

on:
  push:
    branches:
      - ci-push-1x
jobs:
  dynamic_build:
    #if: ${{ false }}  # stop
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup meson
      shell: bash
      run: |
        echo "I'm running on GitHub."
        echo "===== python3 ====="
        python3 -c "import sys; print(sys.version)"
        echo
        echo "===== meson ====="
        pip3 install meson
        meson -v
        echo
        echo "===== clang ====="
        clang -v
        echo
        echo "===== clang 15 ====="
        $(brew --prefix llvm@15)/bin/clang -v
        echo
        echo "===== ninja ====="
        #brew update
        brew install ninja
        #brew upgrade
        ninja --version
        echo
        echo "install tree"
        brew install tree

    - name: Build
      shell: bash
      run: |
        CC=$(brew --prefix llvm@15)/bin/clang CXX=$(brew --prefix llvm@15)/bin/clang++ meson setup --prefix=${{github.workspace}}/thorvg -Dlog=true \
          -Dsavers="all" -Dbindings="capi" -Dtools="all" ${{github.workspace}}/build .

        #meson compile -C ${{github.workspace}}/build
        meson compile -C ${{github.workspace}}/build --verbose
        meson install -C ${{github.workspace}}/build

        echo "tree"
        tree -h ${{github.workspace}}/thorvg/

    - name: Tar files
      run: |
        mkdir ${{github.workspace}}/tar
        cd ${{github.workspace}}/thorvg/ && tar -cvf ${{github.workspace}}/tar/thorvg_mac_dynamic.tar *

    - uses: actions/upload-artifact@v3
      with:
        name: thorvg_mac_dynamic
        path: ${{github.workspace}}/tar



  static_build:
    #if: ${{ false }}  # stop
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup meson
      shell: bash
      run: |
        echo "===== python3 ====="
        python3 -c "import sys; print(sys.version)"
        echo
        echo "===== meson ====="
        pip3 install meson
        meson -v
        echo
        echo "===== clang ====="
        clang -v
        echo
        echo "===== clang 15 ====="
        $(brew --prefix llvm@15)/bin/clang -v
        echo
        echo "===== ninja ====="
        brew install ninja
        ninja --version
        echo
        echo "install tree"
        brew install tree

    - name: Build
      shell: bash
      run: |
        CC=$(brew --prefix llvm@15)/bin/clang CXX=$(brew --prefix llvm@15)/bin/clang++ meson setup --prefix=${{github.workspace}}/thorvg \
            --default-library static -Dlog=true -Dsavers="all" -Dbindings="capi" -Dtools="all" ${{github.workspace}}/build .

        meson compile -C ${{github.workspace}}/build
        #meson compile -C ${{github.workspace}}/build --verbose
        meson install -C ${{github.workspace}}/build

        echo "tree"
        tree -h ${{github.workspace}}/thorvg/

    - name: Tar files
      run: |
        mkdir ${{github.workspace}}/tar
        cd ${{github.workspace}}/thorvg/ && tar -cvf ${{github.workspace}}/tar/thorvg_mac_static.tar *

    - uses: actions/upload-artifact@v3
      with:
        name: thorvg_mac_static
        path: ${{github.workspace}}/tar

